version: '3.9'

services:
  db1:
    image: postgres:15
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
    ports:
      - "5432:5432"

  db2:
    image: postgres:15
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_DB: database2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
    ports:
      - "5433:5432"
