spring:
  cloud:
    gateway:
      routes:
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
  application:
    name: gateway-service

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
